In [1]:
import pandas as pd
import json
input_name = "wall-ovens_raw"
output_name = f"{input_name.split('_')[0]}_extracted.csv"
output_name2 = f"{input_name.split('_')[0]}_clean.csv"

# Remove parentheses around input_name in the file path
df_unclean = pd.read_csv(f"{input_name}.csv")

In [2]:
# Total number of rows and columns in the DataFrame
total_rows, total_columns =df_unclean.shape
print("Total number of rows:", total_rows)
print("Total number of columns:", total_columns)

# Total number of unique 'id's
total_unique_ids = df_unclean['id'].nunique()
print("Total number of unique 'id's:", total_unique_ids)

Total number of rows: 100
Total number of columns: 67
Total number of unique 'id's: 100

In [3]:
# Assuming 'ean' is the column name in your DataFrame
total_rows_ean = df_unclean['ean'].shape[0]
print("Total number of rows in 'ean' column:", total_rows_ean)


missing_values_ean = df_unclean['ean'].isnull().sum()
print("Total number of missing values in 'ean' column:", missing_values_ean)

# Total number of unique 'id's
total_unique_ids = df_unclean['ean'].nunique()
print("Total number of unique 'ean's:", total_unique_ids)

Total number of rows in 'ean' column: 100
Total number of missing values in 'ean' column: 11
Total number of unique 'ean's: 89

In [4]:
df_unclean.head()

,id,apiURLs,asins,brand,canonicalBrand,categories,colors,count,dateAdded,dateUpdated,...,taxonomyLevel6,taxonomyLevel7,taxonomyLevel8,taxonomyLevel9,upc,upce,upca,vin,websiteIDs,weight
0,XA3iPXUBo6SyyXo0Z2b-,NaN,NaN,Summit Appliance,NaN,"Wall Ovens,Appliances,Ranges, Cooktops & Ovens...",NaN,NaN,2020-10-18T22:44:09Z,2024-06-10T14:26:34Z,...,NaN,NaN,NaN,NaN,7.611011e+11,NaN,7.611011e+11,NaN,NaN,170 lbs
1,AWt6O6Zp0Rejpz6vF5Nl,NaN,NaN,Frigidaire,NaN,"Wall Ovens,Appliances,HardGood,Ranges, Cooktop...",NaN,NaN,2019-06-21T13:30:57Z,2024-06-10T14:25:35Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,venue.com-6573748158554,NaN
2,AwvuOHUBo6SyyXo041Tx,NaN,NaN,Fisher & Paykel,NaN,"Wall Ovens,Appliances,Ranges, Cooktops & Ovens...","Stainless Steel,Stainless steel trim,Stainless...",NaN,2020-10-17T23:39:41Z,2024-06-10T14:25:24Z,...,NaN,NaN,NaN,NaN,8.228438e+11,NaN,8.228438e+11,NaN,google.com-10164513239465070861,114.64 lbs
3,MCSl3ncBUbef_7uTOlG1,NaN,NaN,Thor Kitchen,NaN,"Wall Ovens,Appliances,Single Electric Wall Ove...","Stainless Steel,Blue,Stainless steel,Stainless...",NaN,2021-02-26T14:01:46Z,2024-06-10T13:43:28Z,...,NaN,NaN,NaN,NaN,8.500190e+11,NaN,8.500190e+11,NaN,"homedepot.com-316142759,google.com-15505426870...",163 lbs
4,o7pNRHUBvxj1aRne_SYA,NaN,NaN,Viking,NaN,"Wall Ovens,Appliances,Ranges, Cooktops & Ovens...",Arctic Gray,NaN,2020-10-20T04:39:23Z,2024-06-10T13:43:17Z,...,NaN,NaN,NaN,NaN,8.002840e+11,NaN,8.002840e+11,NaN,NaN,261 lbs

In [5]:
df_unclean.columns

Index(['id', 'apiURLs', 'asins', 'brand', 'canonicalBrand', 'categories',
       'colors', 'count', 'dateAdded', 'dateUpdated', 'descriptions',
       'dimension', 'domains', 'ean', 'ean8', 'ean13', 'features',
       'financingAndLeasing', 'flavors', 'gtins', 'imageURLs', 'isbn', 'keys',
       'manufacturer', 'manufacturerNumber', 'merchants',
       'mostRecentPriceAmount', 'mostRecentPriceNonSalesAmount',
       'mostRecentPriceAvailability', 'mostRecentPriceCurrency',
       'mostRecentPriceColor', 'mostRecentPriceSize',
       'mostRecentPriceCondition', 'mostRecentPriceIsSale',
       'mostRecentPriceDomain', 'mostRecentPriceSourceURL',
       'mostRecentPriceDate', 'mostRecentPriceFirstDateSeen',
       'mostRecentPriceByDomain', 'name', 'prices', 'primaryCategories',
       'primaryImageURLs', 'quantities', 'reviews', 'sdsURLs',
       'secondaryCategories', 'sizes', 'skus', 'sourceURLs', 'stockNum',
       'taxonomy', 'taxonomyLevel1', 'taxonomyLevel2', 'taxonomyLevel3',
       'taxonomyLevel4', 'taxonomyLevel5', 'taxonomyLevel6', 'taxonomyLevel7',
       'taxonomyLevel8', 'taxonomyLevel9', 'upc', 'upce', 'upca', 'vin',
       'websiteIDs', 'weight'],
      dtype='object')

In [6]:
# Sample DataFrame
data = df_unclean[['id' , 'ean' , 'manufacturerNumber' , 'upc' , 'features']]
df = pd.DataFrame(data)

In [7]:
df.head()

,id,ean,manufacturerNumber,upc,features
0,XA3iPXUBo6SyyXo0Z2b-,7.611011e+11,TTM7882BEKW,7.611011e+11,"[{""key"":""Towel bar handles"",""value"":[""Curved h..."
1,AWt6O6Zp0Rejpz6vF5Nl,NaN,NaN,NaN,"[{""value"":[""No""],""key"":""App-Controlled""},{""val..."
2,AwvuOHUBo6SyyXo041Tx,8.228438e+11,OB24SCDEPX1,8.228438e+11,"[{""key"":""Sabbath Mode"",""value"":[""No"",""Yes"",""tr..."
3,MCSl3ncBUbef_7uTOlG1,8.500190e+11,NaN,8.500190e+11,"[{""key"":""Actual Width (Inches)"",""value"":[""30""]..."
4,o7pNRHUBvxj1aRne_SYA,8.002840e+11,VSOE530AG,8.002840e+11,"[{""key"":""What's Included"",""value"":[""Rack"",""Vik..."

In [8]:
import json
import numpy as np
# Function to extract keys from 'features' column
def extract_keys(row):
    try:
        features = row['features']
        if isinstance(features, str):
            features_list = json.loads(features)
            keys = [item['key'] for item in features_list]
        else:
            keys = []
    except (json.JSONDecodeError, TypeError):
        keys = []
    return keys

# Apply function to each row
df['list_of_keys_from_features'] = df.apply(extract_keys, axis=1)

df.head(5)

,id,ean,manufacturerNumber,upc,features,list_of_keys_from_features
0,XA3iPXUBo6SyyXo0Z2b-,7.611011e+11,TTM7882BEKW,7.611011e+11,"[{""key"":""Towel bar handles"",""value"":[""Curved h...",[]
1,AWt6O6Zp0Rejpz6vF5Nl,NaN,NaN,NaN,"[{""value"":[""No""],""key"":""App-Controlled""},{""val...","[App-Controlled, Depth Without Handle, Depth W..."
2,AwvuOHUBo6SyyXo041Tx,8.228438e+11,OB24SCDEPX1,8.228438e+11,"[{""key"":""Sabbath Mode"",""value"":[""No"",""Yes"",""tr...",[]
3,MCSl3ncBUbef_7uTOlG1,8.500190e+11,NaN,8.500190e+11,"[{""key"":""Actual Width (Inches)"",""value"":[""30""]...","[Actual Width (Inches), CSA Listed, Sabbath Mo..."
4,o7pNRHUBvxj1aRne_SYA,8.002840e+11,VSOE530AG,8.002840e+11,"[{""key"":""What's Included"",""value"":[""Rack"",""Vik...","[What's Included, Amperage At 208 Volts, Oven ..."

In [9]:
df.dtypes

id                             object
ean                           float64
manufacturerNumber             object
upc                           float64
features                       object
list_of_keys_from_features     object
dtype: object

In [10]:
df.to_csv(output_name , index=False)

In [11]:
total_rows, total_columns = df.shape
print("Total number of rows:", total_rows)
print("Total number of columns:", total_columns)

Total number of rows: 100
Total number of columns: 6

In [12]:
# Remove rows where column "list_of_keys_from_features" has an entry "[]"
df = df[df['list_of_keys_from_features'].apply(len) > 0]

# Check total number of rows and columns of the DataFrame again
total_rows_after_removal, total_columns_after_removal = df.shape
print("Total number of rows after removal:", total_rows_after_removal)
print("Total number of columns after removal:", total_columns_after_removal)

Total number of rows after removal: 50
Total number of columns after removal: 6

In [13]:
df.to_csv(output_name2, index=False)