In [2]:
import pandas as pd
import json
input_name = "icemakers_raw"
output_name = f"{input_name.split('_')[0]}_extracted.csv"
output_name2 = f"{input_name.split('_')[0]}_clean.csv"

# Remove parentheses around input_name in the file path
df_unclean = pd.read_csv(f"{input_name}.csv")

In [3]:
# Total number of rows and columns in the DataFrame
total_rows, total_columns =df_unclean.shape
print("Total number of rows:", total_rows)
print("Total number of columns:", total_columns)

# Total number of unique 'id's
total_unique_ids = df_unclean['id'].nunique()
print("Total number of unique 'id's:", total_unique_ids)

Total number of rows: 100
Total number of columns: 67
Total number of unique 'id's: 100

In [4]:
# Assuming 'ean' is the column name in your DataFrame
total_rows_ean = df_unclean['ean'].shape[0]
print("Total number of rows in 'ean' column:", total_rows_ean)


missing_values_ean = df_unclean['ean'].isnull().sum()
print("Total number of missing values in 'ean' column:", missing_values_ean)

# Total number of unique 'id's
total_unique_ids = df_unclean['ean'].nunique()
print("Total number of unique 'ean's:", total_unique_ids)

Total number of rows in 'ean' column: 100
Total number of missing values in 'ean' column: 28
Total number of unique 'ean's: 72

In [5]:
df_unclean.head()

,id,apiURLs,asins,brand,canonicalBrand,categories,colors,count,dateAdded,dateUpdated,...,taxonomyLevel6,taxonomyLevel7,taxonomyLevel8,taxonomyLevel9,upc,upce,upca,vin,websiteIDs,weight
0,AVpfk4RTLJeJML43_weX,NaN,B0052SUOYC,Exact Replacement Parts,NaN,"Home & Garden,Refrigerators & Freezers,Major A...",White,NaN,2014-02-21T04:56:59Z,2024-06-10T14:52:13Z,...,NaN,NaN,NaN,NaN,6.871522e+11,NaN,6.871522e+11,NaN,wilmar.com-537997,3.275 lb.
1,AWRbgTvdIwln0LfXoMv0,NaN,NaN,Whirlpool,NaN,"Freezers,REFRIGERATOR & FREEZER PARTS & ACCESS...","White,white",1,2018-07-02T14:52:19Z,2024-06-10T13:44:10Z,...,"men,protective gear,women","gloves,shirts,accessories",gloves,NaN,8.830494e+11,NaN,8.830494e+11,NaN,"wilmar.com-291773,menards.com-1444446624697",3.9 lb.
2,AW67tzFYUWiPvv7WFbS_,NaN,NaN,GE Profile,NaN,"Ice Makers,Freezers,Appliances,Shop All Ice Ma...","Stainless Steel,stainless steel,Stainless steel",NaN,2019-11-30T09:49:35Z,2024-06-10T04:24:49Z,...,"ice tongs,ice buckets",NaN,NaN,NaN,8.469182e+10,NaN,8.469182e+10,NaN,"lowes.com-602823,brickseek.com-5846856,walmart...",8 lbs
3,AV1d2tS_GV-KLJ3ad0JU,NaN,B00CJ6SJGA,Summit Appliance,NaN,"Major Appliances,Compact Refrigerators,Refrige...",Other,NaN,2017-07-20T02:36:48Z,2024-06-09T19:33:58Z,...,NaN,NaN,NaN,NaN,7.611010e+11,NaN,7.611010e+11,NaN,"walmart.com-42DJBG3TSTDU,lifetechnology.com-38...",120 lbs
4,AVpfUKTv1cnluZ0-icM9,NaN,B00FIYQCSC,Samsung,NaN,"Home & Garden,Refrigerators & Freezers,Major A...",NaN,NaN,2015-05-27T17:09:50Z,2024-06-07T18:18:34Z,...,NaN,NaN,NaN,NaN,7.174492e+11,NaN,7.174492e+11,NaN,google.com-9096407362720936865,1.8 lbs

In [6]:
df_unclean.columns

Index(['id', 'apiURLs', 'asins', 'brand', 'canonicalBrand', 'categories',
       'colors', 'count', 'dateAdded', 'dateUpdated', 'descriptions',
       'dimension', 'domains', 'ean', 'ean8', 'ean13', 'features',
       'financingAndLeasing', 'flavors', 'gtins', 'imageURLs', 'isbn', 'keys',
       'manufacturer', 'manufacturerNumber', 'merchants',
       'mostRecentPriceAmount', 'mostRecentPriceNonSalesAmount',
       'mostRecentPriceAvailability', 'mostRecentPriceCurrency',
       'mostRecentPriceColor', 'mostRecentPriceSize',
       'mostRecentPriceCondition', 'mostRecentPriceIsSale',
       'mostRecentPriceDomain', 'mostRecentPriceSourceURL',
       'mostRecentPriceDate', 'mostRecentPriceFirstDateSeen',
       'mostRecentPriceByDomain', 'name', 'prices', 'primaryCategories',
       'primaryImageURLs', 'quantities', 'reviews', 'sdsURLs',
       'secondaryCategories', 'sizes', 'skus', 'sourceURLs', 'stockNum',
       'taxonomy', 'taxonomyLevel1', 'taxonomyLevel2', 'taxonomyLevel3',
       'taxonomyLevel4', 'taxonomyLevel5', 'taxonomyLevel6', 'taxonomyLevel7',
       'taxonomyLevel8', 'taxonomyLevel9', 'upc', 'upce', 'upca', 'vin',
       'websiteIDs', 'weight'],
      dtype='object')

In [7]:
# Sample DataFrame
data = df_unclean[['id' , 'ean' , 'manufacturerNumber' , 'upc' , 'features']]
df = pd.DataFrame(data)

In [8]:
df.head()

,id,ean,manufacturerNumber,upc,features
0,AVpfk4RTLJeJML43_weX,6.871522e+11,GEIM,6.871522e+11,"[{""key"":""Commercial/Residential"",""value"":[""Res..."
1,AWRbgTvdIwln0LfXoMv0,8.830494e+11,ECKMFEZ2,8.830494e+11,"[{""key"":""What's Included"",""value"":[""Owner's ma..."
2,AW67tzFYUWiPvv7WFbS_,8.469182e+10,PIP70SS,8.469182e+10,"[{""key"":""MSRP"",""value"":[""$284.99"",""$433.42""]},..."
3,AV1d2tS_GV-KLJ3ad0JU,7.611010e+11,NaN,7.611010e+11,"[{""key"":""Title"",""value"":[""Default Title""]},{""k..."
4,AVpfUKTv1cnluZ0-icM9,7.174492e+11,DA97-08059A,7.174492e+11,"[{""value"":[""New""],""key"":""Condition""},{""key"":""D..."

In [9]:
import json
import numpy as np
# Function to extract keys from 'features' column
def extract_keys(row):
    try:
        features = row['features']
        if isinstance(features, str):
            features_list = json.loads(features)
            keys = [item['key'] for item in features_list]
        else:
            keys = []
    except (json.JSONDecodeError, TypeError):
        keys = []
    return keys

# Apply function to each row
df['list_of_keys_from_features'] = df.apply(extract_keys, axis=1)

df.head(5)

,id,ean,manufacturerNumber,upc,features,list_of_keys_from_features
0,AVpfk4RTLJeJML43_weX,6.871522e+11,GEIM,6.871522e+11,"[{""key"":""Commercial/Residential"",""value"":[""Res...","[Commercial/Residential, Item Package Quantity..."
1,AWRbgTvdIwln0LfXoMv0,8.830494e+11,ECKMFEZ2,8.830494e+11,"[{""key"":""What's Included"",""value"":[""Owner's ma...","[What's Included, View Return Policy, EZ Conne..."
2,AW67tzFYUWiPvv7WFbS_,8.469182e+10,PIP70SS,8.469182e+10,"[{""key"":""MSRP"",""value"":[""$284.99"",""$433.42""]},...","[MSRP, What's Included, Hardware Included, Pro..."
3,AV1d2tS_GV-KLJ3ad0JU,7.611010e+11,NaN,7.611010e+11,"[{""key"":""Title"",""value"":[""Default Title""]},{""k...",[]
4,AVpfUKTv1cnluZ0-icM9,7.174492e+11,DA97-08059A,7.174492e+11,"[{""value"":[""New""],""key"":""Condition""},{""key"":""D...","[Condition, Date First Available, New, sSIN - ..."

In [10]:
df.dtypes

id                             object
ean                           float64
manufacturerNumber             object
upc                           float64
features                       object
list_of_keys_from_features     object
dtype: object

In [11]:
df.to_csv(output_name , index=False)

In [12]:
total_rows, total_columns = df.shape
print("Total number of rows:", total_rows)
print("Total number of columns:", total_columns)

Total number of rows: 100
Total number of columns: 6

In [13]:
# Remove rows where column "list_of_keys_from_features" has an entry "[]"
df = df[df['list_of_keys_from_features'].apply(len) > 0]

# Check total number of rows and columns of the DataFrame again
total_rows_after_removal, total_columns_after_removal = df.shape
print("Total number of rows after removal:", total_rows_after_removal)
print("Total number of columns after removal:", total_columns_after_removal)

Total number of rows after removal: 78
Total number of columns after removal: 6

In [14]:
df.to_csv(output_name2, index=False)