In [1]:
import pandas as pd
import json
input_name = "WashingMachinesandDryers_raw"
output_name = f"{input_name.split('_')[0]}_extracted.csv"
output_name2 = f"{input_name.split('_')[0]}_clean.csv"

# Remove parentheses around input_name in the file path
df_unclean = pd.read_csv(f"{input_name}.csv")

In [2]:
# Total number of rows and columns in the DataFrame
total_rows, total_columns =df_unclean.shape
print("Total number of rows:", total_rows)
print("Total number of columns:", total_columns)

# Total number of unique 'id's
total_unique_ids = df_unclean['id'].nunique()
print("Total number of unique 'id's:", total_unique_ids)

Total number of rows: 100
Total number of columns: 67
Total number of unique 'id's: 100

In [3]:
# Assuming 'ean' is the column name in your DataFrame
total_rows_ean = df_unclean['ean'].shape[0]
print("Total number of rows in 'ean' column:", total_rows_ean)


missing_values_ean = df_unclean['ean'].isnull().sum()
print("Total number of missing values in 'ean' column:", missing_values_ean)

# Total number of unique 'id's
total_unique_ids = df_unclean['ean'].nunique()
print("Total number of unique 'ean's:", total_unique_ids)

Total number of rows in 'ean' column: 100
Total number of missing values in 'ean' column: 22
Total number of unique 'ean's: 78

In [4]:
df_unclean.head()

,id,apiURLs,asins,brand,canonicalBrand,categories,colors,count,dateAdded,dateUpdated,...,taxonomyLevel6,taxonomyLevel7,taxonomyLevel8,taxonomyLevel9,upc,upce,upca,vin,websiteIDs,weight
0,yVconnABUbef_7uTwe5d,NaN,NaN,Hotpoint,NaN,"Built in appliances,Appliances,Washer dryers,I...",NaN,NaN,2020-03-03T02:10:35Z,2024-06-11T13:00:17Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,AVpiFQcjilAPnD_xAiix,NaN,B01N65EOJJ,LG,NaN,"Washer & Dryer Event,Front-Loading Washers,Was...",White,NaN,2017-02-03T22:03:08Z,2024-06-11T11:13:44Z,...,NaN,NaN,NaN,NaN,4.823102e+10,NaN,4.823102e+10,NaN,"brickseek.com-502502,google.com-79582989533966...",Per 100 cycles
2,Ra62s3EBPkqI1fUQf81J,NaN,NaN,SAMSUNG,NaN,"Gas Dryers,Major Appliances,Dryers,Appliances,...","Fingerprint Resistant Black Stainless Steel,Bl...",NaN,2020-04-25T23:40:14Z,2024-06-10T04:07:57Z,...,NaN,NaN,NaN,NaN,8.872761e+11,NaN,8.872761e+11,NaN,"brickseek.com-5746960,homedepot.com-206984124",125.66 lbs
3,SYFK9HABvxj1aRneLvWv,NaN,NaN,SAMSUNG,NaN,"Major Appliances,Washer & Dryer Accessories,Ap...","Gray,Grey",NaN,2020-03-19T19:34:27Z,2024-06-10T00:27:22Z,...,NaN,NaN,NaN,NaN,8.872761e+11,NaN,8.872761e+11,NaN,google.com-8649494909598224344,1.98 lbs
4,neSlI3IBUbef_7uTFP54,NaN,NaN,Samsung,NaN,"Pedestals & Organization,Appliances,Pro Audio ...","Azure Blue,brushed black black stainless,Black...",1.0,2020-05-17T17:18:40Z,2024-06-08T17:19:06Z,...,NaN,NaN,NaN,NaN,8.872763e+11,NaN,8.872763e+11,NaN,"lowes.com-1289787,brickseek.com-7485147,google...",36.6 lbs

In [5]:
df_unclean.columns

Index(['id', 'apiURLs', 'asins', 'brand', 'canonicalBrand', 'categories',
       'colors', 'count', 'dateAdded', 'dateUpdated', 'descriptions',
       'dimension', 'domains', 'ean', 'ean8', 'ean13', 'features',
       'financingAndLeasing', 'flavors', 'gtins', 'imageURLs', 'isbn', 'keys',
       'manufacturer', 'manufacturerNumber', 'merchants',
       'mostRecentPriceAmount', 'mostRecentPriceNonSalesAmount',
       'mostRecentPriceAvailability', 'mostRecentPriceCurrency',
       'mostRecentPriceColor', 'mostRecentPriceSize',
       'mostRecentPriceCondition', 'mostRecentPriceIsSale',
       'mostRecentPriceDomain', 'mostRecentPriceSourceURL',
       'mostRecentPriceDate', 'mostRecentPriceFirstDateSeen',
       'mostRecentPriceByDomain', 'name', 'prices', 'primaryCategories',
       'primaryImageURLs', 'quantities', 'reviews', 'sdsURLs',
       'secondaryCategories', 'sizes', 'skus', 'sourceURLs', 'stockNum',
       'taxonomy', 'taxonomyLevel1', 'taxonomyLevel2', 'taxonomyLevel3',
       'taxonomyLevel4', 'taxonomyLevel5', 'taxonomyLevel6', 'taxonomyLevel7',
       'taxonomyLevel8', 'taxonomyLevel9', 'upc', 'upce', 'upca', 'vin',
       'websiteIDs', 'weight'],
      dtype='object')

In [6]:
# Sample DataFrame
data = df_unclean[['id' , 'ean' , 'manufacturerNumber' , 'upc' , 'features']]
df = pd.DataFrame(data)

In [7]:
df.head()

,id,ean,manufacturerNumber,upc,features
0,yVconnABUbef_7uTwe5d,5.054646e+12,NaN,NaN,"[{""key"":""Overall Rating Count"",""value"":[""1""]},..."
1,AVpiFQcjilAPnD_xAiix,4.823102e+10,NaN,4.823102e+10,"[{""key"":""ENERGY STAR Certified"",""value"":[""Yes""..."
2,Ra62s3EBPkqI1fUQf81J,8.872761e+11,NaN,8.872761e+11,"[{""key"":""ENERGY STAR Certified"",""value"":[""Yes""..."
3,SYFK9HABvxj1aRneLvWv,8.872761e+11,NaN,8.872761e+11,"[{""key"":""Date First Available"",""value"":[""June ..."
4,neSlI3IBUbef_7uTFP54,8.872763e+11,WE402NV,8.872763e+11,"[{""key"":""MSRP"",""value"":[""$659.99""]},{""key"":""Ap..."

In [8]:
import json
import numpy as np
# Function to extract keys from 'features' column
def extract_keys(row):
    try:
        features = row['features']
        if isinstance(features, str):
            features_list = json.loads(features)
            keys = [item['key'] for item in features_list]
        else:
            keys = []
    except (json.JSONDecodeError, TypeError):
        keys = []
    return keys

# Apply function to each row
df['list_of_keys_from_features'] = df.apply(extract_keys, axis=1)

df.head(5)

,id,ean,manufacturerNumber,upc,features,list_of_keys_from_features
0,yVconnABUbef_7uTwe5d,5.054646e+12,NaN,NaN,"[{""key"":""Overall Rating Count"",""value"":[""1""]},...","[Overall Rating Count, Washing programmes, Dry..."
1,AVpiFQcjilAPnD_xAiix,4.823102e+10,NaN,4.823102e+10,"[{""key"":""ENERGY STAR Certified"",""value"":[""Yes""...","[ENERGY STAR Certified, Pedestal Model Compati..."
2,Ra62s3EBPkqI1fUQf81J,8.872761e+11,NaN,8.872761e+11,"[{""key"":""ENERGY STAR Certified"",""value"":[""Yes""...","[ENERGY STAR Certified, Pedestal Model Compati..."
3,SYFK9HABvxj1aRneLvWv,8.872761e+11,NaN,8.872761e+11,"[{""key"":""Date First Available"",""value"":[""June ...","[Date First Available, Model Compatibility, Ma..."
4,neSlI3IBUbef_7uTFP54,8.872763e+11,WE402NV,8.872763e+11,"[{""key"":""MSRP"",""value"":[""$659.99""]},{""key"":""Ap...",[]

In [9]:
df.dtypes

id                             object
ean                           float64
manufacturerNumber             object
upc                           float64
features                       object
list_of_keys_from_features     object
dtype: object

In [10]:
df.to_csv(output_name , index=False)

In [11]:
total_rows, total_columns = df.shape
print("Total number of rows:", total_rows)
print("Total number of columns:", total_columns)

Total number of rows: 100
Total number of columns: 6

In [12]:
# Remove rows where column "list_of_keys_from_features" has an entry "[]"
df = df[df['list_of_keys_from_features'].apply(len) > 0]

# Check total number of rows and columns of the DataFrame again
total_rows_after_removal, total_columns_after_removal = df.shape
print("Total number of rows after removal:", total_rows_after_removal)
print("Total number of columns after removal:", total_columns_after_removal)

Total number of rows after removal: 35
Total number of columns after removal: 6

In [13]:
df.to_csv(output_name2, index=False)