In [1]:
import pandas as pd
import json
input_name = "WaterFiltrationSystems_raw"
output_name = f"{input_name.split('_')[0]}_extracted.csv"
output_name2 = f"{input_name.split('_')[0]}_clean.csv"

# Remove parentheses around input_name in the file path
df_unclean = pd.read_csv(f"{input_name}.csv")

In [2]:
# Total number of rows and columns in the DataFrame
total_rows, total_columns =df_unclean.shape
print("Total number of rows:", total_rows)
print("Total number of columns:", total_columns)

# Total number of unique 'id's
total_unique_ids = df_unclean['id'].nunique()
print("Total number of unique 'id's:", total_unique_ids)

Total number of rows: 100
Total number of columns: 67
Total number of unique 'id's: 100

In [3]:
# Assuming 'ean' is the column name in your DataFrame
total_rows_ean = df_unclean['ean'].shape[0]
print("Total number of rows in 'ean' column:", total_rows_ean)


missing_values_ean = df_unclean['ean'].isnull().sum()
print("Total number of missing values in 'ean' column:", missing_values_ean)

# Total number of unique 'id's
total_unique_ids = df_unclean['ean'].nunique()
print("Total number of unique 'ean's:", total_unique_ids)

Total number of rows in 'ean' column: 100
Total number of missing values in 'ean' column: 12
Total number of unique 'ean's: 88

In [4]:
df_unclean.head()

,id,apiURLs,asins,brand,canonicalBrand,categories,colors,count,dateAdded,dateUpdated,...,taxonomyLevel6,taxonomyLevel7,taxonomyLevel8,taxonomyLevel9,upc,upce,upca,vin,websiteIDs,weight
0,AWE_50Q6Iwln0LfXiFsj,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-01-29T03:06:36Z,2024-06-11T03:14:37Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ZACCJABT3GPC43104,NaN,NaN
1,AVpfUgzW1cnluZ0-ijjH,NaN,B00EMI7XOM,Accutemp,NaN,"Accessories,Appliance Accessories,Appliances,S...",NaN,NaN,2015-10-19T17:55:14Z,2024-06-10T16:37:19Z,...,NaN,NaN,NaN,NaN,7.375745e+11,NaN,7.375745e+11,NaN,NaN,NaN
2,yh0f-3IBPkqI1fUQkTjR,NaN,NaN,Techniks,NaN,"Home Improvement,Tools,Power Tool Accessories,...",NaN,NaN,2020-06-28T13:30:49Z,2024-06-10T14:26:46Z,...,NaN,NaN,NaN,NaN,6.502294e+11,NaN,6.502294e+11,NaN,"google.com-16162721469891710220,walmart.com-35...",7.85 LBS
3,AW5JUeRuJa1kp7EkJp21,NaN,NaN,Swift Green Filters,NaN,"Plumbing,Refrigerator Freezer Parts,REFRIGERAT...",White,1 pk,2019-11-08T04:42:13Z,2024-06-10T13:39:47Z,...,NaN,NaN,NaN,NaN,7.793640e+11,NaN,7.793640e+11,NaN,wilmar.com-300461375,0.4 lbs
4,AWoQ3TQcAGTnQPR7mqoU,NaN,NaN,Swift Green Filters,NaN,"Plumbing,Refrigerator Freezer Parts,REFRIGERAT...",NaN,1 pk,2019-04-12T09:10:41Z,2024-06-10T13:39:39Z,...,NaN,NaN,NaN,NaN,7.793640e+11,NaN,7.793640e+11,NaN,"wilmar.com-300461351,wilmar.com-300541977,wilm...",0.5 lbs

In [5]:
df_unclean.columns

Index(['id', 'apiURLs', 'asins', 'brand', 'canonicalBrand', 'categories',
       'colors', 'count', 'dateAdded', 'dateUpdated', 'descriptions',
       'dimension', 'domains', 'ean', 'ean8', 'ean13', 'features',
       'financingAndLeasing', 'flavors', 'gtins', 'imageURLs', 'isbn', 'keys',
       'manufacturer', 'manufacturerNumber', 'merchants',
       'mostRecentPriceAmount', 'mostRecentPriceNonSalesAmount',
       'mostRecentPriceAvailability', 'mostRecentPriceCurrency',
       'mostRecentPriceColor', 'mostRecentPriceSize',
       'mostRecentPriceCondition', 'mostRecentPriceIsSale',
       'mostRecentPriceDomain', 'mostRecentPriceSourceURL',
       'mostRecentPriceDate', 'mostRecentPriceFirstDateSeen',
       'mostRecentPriceByDomain', 'name', 'prices', 'primaryCategories',
       'primaryImageURLs', 'quantities', 'reviews', 'sdsURLs',
       'secondaryCategories', 'sizes', 'skus', 'sourceURLs', 'stockNum',
       'taxonomy', 'taxonomyLevel1', 'taxonomyLevel2', 'taxonomyLevel3',
       'taxonomyLevel4', 'taxonomyLevel5', 'taxonomyLevel6', 'taxonomyLevel7',
       'taxonomyLevel8', 'taxonomyLevel9', 'upc', 'upce', 'upca', 'vin',
       'websiteIDs', 'weight'],
      dtype='object')

In [6]:
# Sample DataFrame
data = df_unclean[['id' , 'ean' , 'manufacturerNumber' , 'upc' , 'features']]
df = pd.DataFrame(data)

In [7]:
df.head()

,id,ean,manufacturerNumber,upc,features
0,AWE_50Q6Iwln0LfXiFsj,NaN,NaN,NaN,"[{""value"":[""2016""],""key"":""Year""},{""value"":[""La..."
1,AVpfUgzW1cnluZ0-ijjH,7.375745e+11,AT0E-2559-2,7.375745e+11,"[{""key"":""sSIN - kmart.com"",""value"":[""A12409125..."
2,yh0f-3IBPkqI1fUQkTjR,6.502294e+11,NaN,6.502294e+11,"[{""key"":""Brand"",""value"":[""Techniks""]}]"
3,AW5JUeRuJa1kp7EkJp21,7.793640e+11,SGF-ADQ401 Rx,7.793640e+11,"[{""key"":""Reduces Chlorine Taste and Odor"",""val..."
4,AWoQ3TQcAGTnQPR7mqoU,7.793640e+11,SGF-LA07 Rx,7.793640e+11,"[{""key"":""Reduces Chlorine Taste and Odor"",""val..."

In [8]:
import json
import numpy as np
# Function to extract keys from 'features' column
def extract_keys(row):
    try:
        features = row['features']
        if isinstance(features, str):
            features_list = json.loads(features)
            keys = [item['key'] for item in features_list]
        else:
            keys = []
    except (json.JSONDecodeError, TypeError):
        keys = []
    return keys

# Apply function to each row
df['list_of_keys_from_features'] = df.apply(extract_keys, axis=1)

df.head(5)

,id,ean,manufacturerNumber,upc,features,list_of_keys_from_features
0,AWE_50Q6Iwln0LfXiFsj,NaN,NaN,NaN,"[{""value"":[""2016""],""key"":""Year""},{""value"":[""La...","[Year, Trim, Model, Make, Product Features]"
1,AVpfUgzW1cnluZ0-ijjH,7.375745e+11,AT0E-2559-2,7.375745e+11,"[{""key"":""sSIN - kmart.com"",""value"":[""A12409125...","[sSIN - kmart.com, Part Number - kmart.com, Cl..."
2,yh0f-3IBPkqI1fUQkTjR,6.502294e+11,NaN,6.502294e+11,"[{""key"":""Brand"",""value"":[""Techniks""]}]",[Brand]
3,AW5JUeRuJa1kp7EkJp21,7.793640e+11,SGF-ADQ401 Rx,7.793640e+11,"[{""key"":""Reduces Chlorine Taste and Odor"",""val...","[Reduces Chlorine Taste and Odor, Vendor Name,..."
4,AWoQ3TQcAGTnQPR7mqoU,7.793640e+11,SGF-LA07 Rx,7.793640e+11,"[{""key"":""Reduces Chlorine Taste and Odor"",""val...","[Reduces Chlorine Taste and Odor, Vendor Name,..."

In [9]:
df.dtypes

id                             object
ean                           float64
manufacturerNumber             object
upc                           float64
features                       object
list_of_keys_from_features     object
dtype: object

In [10]:
df.to_csv(output_name , index=False)

In [11]:
total_rows, total_columns = df.shape
print("Total number of rows:", total_rows)
print("Total number of columns:", total_columns)

Total number of rows: 100
Total number of columns: 6

In [12]:
# Remove rows where column "list_of_keys_from_features" has an entry "[]"
df = df[df['list_of_keys_from_features'].apply(len) > 0]

# Check total number of rows and columns of the DataFrame again
total_rows_after_removal, total_columns_after_removal = df.shape
print("Total number of rows after removal:", total_rows_after_removal)
print("Total number of columns after removal:", total_columns_after_removal)

Total number of rows after removal: 63
Total number of columns after removal: 6

In [13]:
df.to_csv(output_name2, index=False)